using AwesomeAssertions;

namespace LoggerUsage.Tests;

public class PipelineHardeningTests
{
    [Fact]
    public async Task ExtractLoggerUsagesWithSolutionAsync_PreCancelledToken_PropagatesCancellation()
    {
        var compilation = await TestUtils.CreateCompilationAsync(
            """
            using Microsoft.Extensions.Logging;

            public sealed class Service
            {
                public void Run(ILogger logger) =>
                    logger.LogInformation("Message {Value}", 42);
            }
            """);
        var extractor = TestUtils.CreateLoggerUsageExtractor();
        using var cancellationSource = new CancellationTokenSource();
        cancellationSource.Cancel();

        var action = () => extractor.ExtractLoggerUsagesWithSolutionAsync(
            compilation,
            cancellationToken: cancellationSource.Token);

        await action.Should().ThrowAsync<OperationCanceledException>();
    }

    [Fact]
    public async Task ExtractLoggerUsagesWithSolutionAsync_GeneratedHeaderExcluded_UserAuthoredGeneratedSuffixIncluded()
    {
        var compilation = await TestUtils.CreateCompilationAsync(
            (
                """
                // <auto-generated/>
                using Microsoft.Extensions.Logging;

                public sealed class GeneratedService
                {
                    public void Run(ILogger logger) =>
                        logger.LogInformation("Generated message");
                }
                """,
                "GeneratedService.g.cs"),
            (
                """
                using Microsoft.Extensions.Logging;

                public sealed class UserAuthoredService
                {
                    public void Run(ILogger logger) =>
                        logger.LogInformation("User-authored message");
                }
                """,
                "UserAuthoredService.g.cs"));
        var extractor = TestUtils.CreateLoggerUsageExtractor();

        var result = await extractor.ExtractLoggerUsagesWithSolutionAsync(compilation);

        result.Results.Should().ContainSingle()
            .Which.MessageTemplate.Should().Be("User-authored message");
    }
}
