using Microsoft.CodeAnalysis;

namespace LoggerUsage.Utilities;

internal static class GeneratedCodeDetector
{
    private const int HeaderLength = 2_048;
    private const string AutoGeneratedMarker = "<auto-generated";
    private const string AlternateAutoGeneratedMarker = "<autogenerated";

    public static bool IsGenerated(SyntaxTree syntaxTree, CancellationToken cancellationToken)
    {
        var text = syntaxTree.GetText(cancellationToken);
        var length = Math.Min(text.Length, HeaderLength);
        if (length == 0)
        {
            return false;
        }

        var header = text.ToString(new Microsoft.CodeAnalysis.Text.TextSpan(0, length));
        return header.Contains(AutoGeneratedMarker, StringComparison.OrdinalIgnoreCase)
            || header.Contains(AlternateAutoGeneratedMarker, StringComparison.OrdinalIgnoreCase);
    }
}
