name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet run --project test/LoggerUsage.Tests --coverage --coverage-output-format cobertura --coverage-output coverage.cobertura.xml
    - name: Generate Code Coverage Report
      run: |
        # using github:
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:coverage.cobertura.xml -targetdir:coveragereport -reporttypes:MarkdownSummaryGithub

